services:

  frontend:
    build: app/
    image: react-app
    container_name: react-container
    volumes:
      - "./app:/src/app"
      - "/src/app/node_modules"
    ports:
      - "5173:5173"


  backend:
    build: server/
    image: "api-server"
    volumes:
      - "./server:/src/app"
    container_name: api-container
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
    depends_on:
      - database

  database:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend-db
      POSTGRES_PASSWORD: docker
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data postgres